use crate::error::{ForgeError, Result};
use crate::models::ForgeInstallResult;

/// Determine the correct start script filename for the current OS.
pub fn start_script_filename() -> &'static str {
    if cfg!(windows) {
        "run.bat"
    } else {
        "run.sh"
    }
}

/// Parse a Forge `run.bat` or `run.sh` start script to extract the
/// `@libraries/...` argument path used to launch the server.
///
/// The script typically contains a line like:
/// ```text
/// java @libraries/net/minecraftforge/forge/1.20.1-47.3.22/unix_args.txt %*
/// ```
///
/// This function extracts the `@libraries/...` portion and returns an
/// install result with `server_jar` cleared (since Forge uses the
/// libraries manifest instead of a direct JAR).
pub fn parse_start_script(script_content: &str, exit_code: i32) -> Result<ForgeInstallResult> {
    for line in script_content.lines() {
        if !line.starts_with("java") {
            continue;
        }
        if let Some(index) = line.find("@libraries") {
            let java_args = line[index..]
                .split_whitespace()
                .next()
                .unwrap_or(line[index..].trim())
                .to_string();

            return Ok(ForgeInstallResult {
                server_jar: String::new(),
                java_args,
                exit_code,
            });
        }
    }

    Err(ForgeError::ScriptParseError {
        reason: "Could not find @libraries argument in start script".to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_windows_bat() {
        let content = r#"@echo off
java @libraries/net/minecraftforge/forge/1.20.1-47.3.22/win_args.txt %*
pause
"#;
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/minecraftforge/forge/1.20.1-47.3.22/win_args.txt"
        );
        assert_eq!(result.server_jar, "");
        assert_eq!(result.exit_code, 0);
    }

    #[test]
    fn test_parse_unix_sh() {
        let content = r#"#!/usr/bin/env sh
java @libraries/net/minecraftforge/forge/1.20.1-47.3.22/unix_args.txt "$@"
"#;
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/minecraftforge/forge/1.20.1-47.3.22/unix_args.txt"
        );
    }

    #[test]
    fn test_parse_no_libraries() {
        let content = "echo Hello\npause\n";
        let result = parse_start_script(content, 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_start_script_filename() {
        let name = start_script_filename();
        if cfg!(windows) {
            assert_eq!(name, "run.bat");
        } else {
            assert_eq!(name, "run.sh");
        }
    }

    #[test]
    fn test_parse_preserves_exit_code() {
        let content = "java @libraries/some/path/args.txt %*\n";
        let result = parse_start_script(content, 42).unwrap();
        assert_eq!(result.exit_code, 42);
    }

    #[test]
    fn test_parse_with_extra_java_flags() {
        let content =
            "java -Xmx4G @libraries/net/minecraftforge/forge/1.20.1-47.3.22/win_args.txt %*\n";
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/minecraftforge/forge/1.20.1-47.3.22/win_args.txt"
        );
    }

    #[test]
    fn test_parse_script_with_comments_and_blank_lines() {
        let content = r#"@echo off
REM Forge start script
REM Generated by installer

java @libraries/net/minecraftforge/forge/1.20.1-47.3.22/win_args.txt %*
pause
"#;
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/minecraftforge/forge/1.20.1-47.3.22/win_args.txt"
        );
    }

    #[test]
    fn test_parse_empty_script() {
        let result = parse_start_script("", 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_java_line_without_libraries() {
        let content = "java -jar server.jar nogui\n";
        let result = parse_start_script(content, 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_script_error_message() {
        let content = "echo nothing useful\n";
        let err = parse_start_script(content, 0).unwrap_err();
        match err {
            ForgeError::ScriptParseError { reason } => {
                assert!(reason.contains("@libraries"));
            }
            _ => panic!("Expected ScriptParseError"),
        }
    }

    #[test]
    fn test_parse_old_forge_style_with_long_path() {
        let content =
            "java @libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/unix_args.txt \"$@\"\n";
        let result = parse_start_script(content, 0).unwrap();
        assert!(result.java_args.contains("1.12.2-14.23.5.2860"));
    }

    #[test]
    fn test_parse_server_jar_always_empty() {
        let content = "java @libraries/test/args.txt %*\n";
        let result = parse_start_script(content, 0).unwrap();
        assert!(result.server_jar.is_empty());
    }
}
