use crate::error::{NeoForgeError, Result};
use crate::models::NeoForgeInstallResult;

/// Determine the correct start script filename for the current OS.
pub fn start_script_filename() -> &'static str {
    if cfg!(windows) {
        "run.bat"
    } else {
        "run.sh"
    }
}

/// Parse a NeoForge `run.bat` or `run.sh` start script to extract the
/// `@libraries/...` argument path used to launch the server.
///
/// The script typically contains a line like:
/// ```text
/// java @libraries/net/neoforged/neoforge/21.4.108/unix_args.txt %*
/// ```
///
/// This function extracts the `@libraries/...` portion and returns an
/// install result with `server_jar` cleared (since NeoForge uses the
/// libraries manifest instead of a direct JAR).
pub fn parse_start_script(script_content: &str, exit_code: i32) -> Result<NeoForgeInstallResult> {
    for line in script_content.lines() {
        if !line.starts_with("java") {
            continue;
        }
        if let Some(index) = line.find("@libraries") {
            let java_args = line[index..]
                .split_whitespace()
                .next()
                .unwrap_or(line[index..].trim())
                .to_string();

            return Ok(NeoForgeInstallResult {
                server_jar: String::new(),
                java_args,
                exit_code,
            });
        }
    }

    Err(NeoForgeError::ScriptParseError {
        reason: "Could not find @libraries argument in start script".to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_neoforge_bat() {
        let content = r#"@echo off
java @libraries/net/neoforged/neoforge/21.4.108/win_args.txt %*
pause
"#;
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/neoforged/neoforge/21.4.108/win_args.txt"
        );
        assert_eq!(result.server_jar, "");
        assert_eq!(result.exit_code, 0);
    }

    #[test]
    fn test_parse_neoforge_sh() {
        let content = r#"#!/usr/bin/env sh
java @libraries/net/neoforged/neoforge/21.4.108/unix_args.txt "$@"
"#;
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/neoforged/neoforge/21.4.108/unix_args.txt"
        );
    }

    #[test]
    fn test_parse_no_libraries() {
        let content = "echo Hello\npause\n";
        let result = parse_start_script(content, 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_preserves_exit_code() {
        let content = "java @libraries/some/path/args.txt %*\n";
        let result = parse_start_script(content, 7).unwrap();
        assert_eq!(result.exit_code, 7);
    }

    #[test]
    fn test_parse_with_jvm_flags() {
        let content =
            "java -Xmx8G -Xms2G @libraries/net/neoforged/neoforge/21.4.108/win_args.txt %*\n";
        let result = parse_start_script(content, 0).unwrap();
        assert_eq!(
            result.java_args,
            "@libraries/net/neoforged/neoforge/21.4.108/win_args.txt"
        );
    }

    #[test]
    fn test_parse_script_with_comments() {
        let content = r#"#!/usr/bin/env sh
# NeoForge server start script
# Auto-generated by installer

java @libraries/net/neoforged/neoforge/21.4.108/unix_args.txt "$@"
"#;
        let result = parse_start_script(content, 0).unwrap();
        assert!(result.java_args.contains("neoforged"));
    }

    #[test]
    fn test_parse_empty_script() {
        let result = parse_start_script("", 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_java_without_libraries() {
        let content = "java -jar server.jar nogui\n";
        let result = parse_start_script(content, 0);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_error_message_content() {
        let content = "echo nothing\n";
        let err = parse_start_script(content, 0).unwrap_err();
        match err {
            NeoForgeError::ScriptParseError { reason } => {
                assert!(reason.contains("@libraries"));
            }
            _ => panic!("Expected ScriptParseError"),
        }
    }

    #[test]
    fn test_parse_server_jar_always_empty() {
        let content = "java @libraries/test/args.txt %*\n";
        let result = parse_start_script(content, 0).unwrap();
        assert!(result.server_jar.is_empty());
    }

    #[test]
    fn test_start_script_filename() {
        let name = start_script_filename();
        if cfg!(windows) {
            assert_eq!(name, "run.bat");
        } else {
            assert_eq!(name, "run.sh");
        }
    }
}
