CREATE TABLE IF NOT EXISTS servers
(
	id                INTEGER PRIMARY KEY AUTOINCREMENT,
	name              TEXT NOT NULL,
	directory         TEXT NOT NULL,
	java_executable   TEXT NOT NULL,
	java_args         TEXT NOT NULL,
	max_memory        INTEGER NOT NULL DEFAULT 4,
	min_memory        INTEGER NOT NULL DEFAULT 2,
	minecraft_args    TEXT NOT NULL DEFAULT 'nogui',
	server_jar        TEXT NOT NULL DEFAULT '',
	upnp              INTEGER NOT NULL DEFAULT 0,
	status            INTEGER NOT NULL DEFAULT 0,
	auto_start        INTEGER NOT NULL DEFAULT 0,
	auto_restart      INTEGER NOT NULL DEFAULT 1,
	backup_enabled    INTEGER NOT NULL DEFAULT 1,
	backup_cron       TEXT NOT NULL DEFAULT '0 0 * * * *',
	backup_retention  INTEGER NOT NULL DEFAULT 7,
	description       TEXT,
	minecraft_version TEXT DEFAULT '',
	server_type       INTEGER NOT NULL DEFAULT 0,
	loader_version    TEXT DEFAULT NULL,
	owner_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	created_at        INTEGER NOT NULL DEFAULT (STRFTIME('%s', 'now')),
	updated_at        INTEGER NOT NULL DEFAULT (STRFTIME('%s', 'now')),
	last_started      INTEGER DEFAULT NULL,
	last_update_check INTEGER DEFAULT NULL,
	update_available  INTEGER NOT NULL DEFAULT 0,
	latest_version    TEXT DEFAULT NULL
);
