CREATE TABLE IF NOT EXISTS `servers`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name`              VARCHAR(255) NOT NULL,
	`directory`         VARCHAR(255) NOT NULL,
	`java_executable`   VARCHAR(512) NOT NULL,
	`java_args`         TEXT NOT NULL,
	`max_memory`        TINYINT NOT NULL DEFAULT 4,
	`min_memory`        TINYINT NOT NULL DEFAULT 2,
	`minecraft_args`    VARCHAR(255) NOT NULL DEFAULT 'nogui',
	`server_jar`        VARCHAR(255) NOT NULL DEFAULT '',
	`upnp`              TINYINT NOT NULL DEFAULT 0,
	`status`            TINYINT NOT NULL DEFAULT 0,
	`auto_start`        BOOLEAN NOT NULL DEFAULT 0,
	`auto_restart`      BOOLEAN NOT NULL DEFAULT 1,
	`backup_enabled`    BOOLEAN NOT NULL DEFAULT 1,
	`backup_cron`       VARCHAR(50) NOT NULL DEFAULT '0 0 * * * *',
	`backup_retention`  INT NOT NULL DEFAULT 7,
	`description`       TEXT,
	`minecraft_version` VARCHAR(50) DEFAULT '',
	`server_type`       TINYINT NOT NULL DEFAULT 0,
	`loader_version`    VARCHAR(50) DEFAULT NULL,
	`owner_id` INT UNSIGNED NOT NULL,
	`created_at`        INT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
	`updated_at`        INT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
	`last_started`      INT DEFAULT NULL,
	`last_update_check` INT DEFAULT NULL,
	`update_available`  BOOLEAN NOT NULL DEFAULT 0,
	`latest_version`    VARCHAR(50) DEFAULT NULL,
	FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
